### PR TITLE
Add 'while Channelling' mod support

### PR DESCRIPTION
**Pull request by markuspersson**
This will enable the 'while channelling' mods from the new Singular Focus and Lucidity nodes.
Added a new config option in combat called "Are you channelling?".

### CODE REVIEW

**Comment by arne-z** [comment]
Apologies in advance if I am making wrong assumptions since I am not familiar enough with the codebase to tell whether this is a good solution:  
I am more speaking from a users perspective here, but isn't channeling something that could be inferred from the main skill itself?  
Skills should only be affected by channeling mods if they are either a channeling skill or cast via "cast while channeling" correct?  
Is this just the most simple solution for the chanelling mods or are you trying to accommodate a situation like someone fully stacking a blade vortex and then casting a channeling skill while the BV is still dealing damage? This seems like too much of an edge case though.

Thank you for the work you put into the tool!

**Comment by markuspersson** [comment]
I’m also pretty new to the code base and was just following the same pattern as with other effects :)

I agree with you that it would definitely be better to infer from the main skill, good call!

Is this possible to do? 
@Openarl maybe you could shed some light on this?

**Comment by ianmarmour** [comment]
So I was looking through this codebase last night it looks like currently there isn't support for channeling on the active skill flags. You can look into adding support for the new flag, it's already being exported by pypoe exporter. If you look into the export folder and the skillList you'll see channeling but if you actually look at the skills lua there's no active flag for channeling. 

It appears like OpenArl already got this working in the latest commit or someone else did and he merged it.

**Comment by markuspersson** [comment]
I have removed the extra checkbox in the Calcs section. Instead we know check if the selected main skill is a channelling skill. Thanks @arne-z for the suggestion and please check if you want and have the time :)

@ianmarmour @Openarl, the only data that I found regarding skill tags was in the `tagString`. The solution now is to match that string with a keyword and then update the condition accordingly. 
I'm not 100% happy with this approach because string matching. I would much rather just get it from the flags (or tags) directly so that we can do: `mainSkill.skillFlags.channelling`. However when I check the existing data the tags table is always empty and the only place where I see 'channelling' is on the tagString.

Let me know what you think.

**Comment by arne-z** [comment]
@markuspersson In https://github.com/Openarl/PathOfBuilding/blob/master/Modules/ModParser-3_0.lua you can find that the mod for channeling nodes on gear or skilltree is used as such:

	["with channelling skills"] = { tag = { type = "SkillType", skillType = SkillType.Channelled } },

That should get you around the string checking. This doesn't fully solve the "while channelling" issue since it doesn't handle the case of using a skill with cast while channeling. I would look at the 
https://github.com/Openarl/PathOfBuilding/blob/master/Export/Skills/sup_int.txt
for how the cast while channeling support works.

**Comment by Openarl** [comment]
Already implemented.

**Pull request closed without merging**
