### PR TITLE
skills: add radius (20) to vortex

### LINKED ISSUE #1304: vortex doesn't show aoe radius
Vortex is an aoe skill so it should show the radius stat somewhere. It doesn't appear to have a radius set in baseMods so I guess fixing this to whatever the correct value should be would resolve it?

### PR DESCRIPTION
**Pull request by zmike**
closes #1304

### CODE REVIEW

**Comment by Openarl** [comment]
The gem data files must not be edited directly! They are automatically
generated from the data export system from the template files located in
/Export/Skills/; you should edit those instead, and ideally run the skill
exporter if you are able to set it up, but I can run it myself once I pull
your commit if you don't.

**Comment by zmike** [comment]
Oh, that's interesting. It doesn't seem like Vortex exists anywhere in that directory though?

It would be great if there was a bit more info about this sort of thing in the CONTRIBUTING file.

**Comment by zmike** [comment]
Ah, I guess it's FrostBoltNova in Export/Skills? I have no idea what or where the exporter is, but I think this is what it would look like after running...

**Comment by Openarl** [comment]
Yep, that's all correct; FrostBoltNova is the internal name for the skill.

The exporter is the set of Lua scripts in the Export folder; I haven't
detailed the setup for that system yet because it is rather involved, since
it relies on PyPoE to export the data files from the .ggpk.

**Pull request merged**
