### PR TITLE
Update bonus applied by activating Feeding Frenzy

### PR DESCRIPTION
**Pull request by kjerstadius**
I noticed that activating Feeding Frenzy in the Configuration tab was still applying the 10% damage bonus which was removed in 3.10 (see https://www.pathofexile.com/forum/view-thread/2784310). While removing it I also noticed that the movement speed and speed bonuses were applying at incorrect amounts (10% instead of 15%). This PR fixes both of these things.

I'm unsure whether anything needs or should be done with the Feeding Frenzy skill in `Data/3_0/Skills/sup_int.lua` though. There's still a `Damage` `MinionModifier` in there, but it never seems to activate.

### CODE REVIEW

**Comment by Ydoum** [comment]
Pretty sure it's just a callout to the function that tells it how much damage it needs to add (from the file you modified).

**Comment by AnnanFay** [comment]
> I noticed that activating Feeding Frenzy in the Configuration tab was still applying the 10% damage bonus which was removed in 3.10 (see https://www.pathofexile.com/forum/view-thread/2784310)

The thread you link to does not say this (bold mine).

> Feeding Frenzy Support
> * Now gives minions from supported skills 25% chance to grant Feeding Frenzy to you on hit at gem level 1, up to 44% at gem level 20 (previously 25% at all gem levels).
> * No longer causes minions from **supported skills** to deal more damage while you have Feeding Frenzy.

Before this patch FFS had this line:

> Minions from Supported Skills deal (5-14)% more Damage while you have Feeding Frenzy

The patch did not change the more damage modifier on the feeding frenzy buff, only the damage for supported skills.

**Comment by kjerstadius** [comment]
@AnnanFay Good catch! A small but very important distinction. It's a nice surprise for me since it means feeding frenzy was nerfed less than I thought.

I have updated my changes to only correct the movement, attack and cast speed bonuses.

**Comment by kjerstadius** [comment]
I realized that I was wrong here. The movement, attack and cast speed bonuses were lowered in 3.9 (Metamorph). So the values are correct, but the tooltip info is wrong. This issue is fixed in the community fork though, so I'll just close this PR.

**Pull request closed without merging**
