### PR TITLE
Add mods from Vixen's Entrapment, Embroidered Gloves

### PR DESCRIPTION
**Pull request by markuspersson**
### New config option:
- "# of Curses on Enemy:". Will displayed at all times in Effective DPS. I can flag it if you want.

### New supported mods from Vixen's Entrapment:
- %x increased cast speed with curse skills
- x% of Spell Damage Leeched as Energy Shield for each Curse on Enemy

### New supported mods from tree:
- x% of Spell Damage Leeched as Energy Shield 

### ES Leech:
Basically I have mimicked the implemenation of mana and life leeches with the difference that ES Leech has a max leech cap rate of 10% of the ES pool (`MaxEnergyShieldLeechRate`). I read today that all leech caps would now be 10% but I have not added that in this change.

### **NOTE: Ghost Reaver is not updated with the new ES Leech rates!**

I started on this change a couple of days ago, before the patch notes, just to try it out and learning the code base. 
I think the basics is correct but the interaction with Ghost Reaver is not really there yet.
What I did for now was to take the previous implementation of Ghost Reaver and add it together with the new ES leech to get a combined value. However it is still using the life leech rates which should not be the case anymore, it should be the es leech rates. 
I also didn't update the calc sections to use the life leech values combined with the es leech, now it is only using the new: `{damageType}EnergyShieldLeech`

My thoughts on this is we do one of the following:
1. We use this to save some time and fix the Ghost Reaver interaction with a new PR (still need to update the mod to actually make it work again anyway even if its just a minor parser change).
2. I revert the changes I've done to Ghost Reaver and we only test with the ES Leech mods. 
3. We discard this because I got it all wrong :)

Either way I would like to get some extra eyes on this!

@Openarl, what do you think? Maybe there's some bits and pieces we can use ;)

### CODE REVIEW

**Comment by Openarl** [comment]
I've actually just implemented ES leech in the 1.4.130 update which is being released shortly. I might be able to use some of the other changes, though.

**Comment by markuspersson** [comment]
Cool! Looking forward to see the changes. Let me know if you need anything more from me regarding this change

**Comment by Openarl** [comment]
Well, updating it so I don't have a million merge conflicts would be a start ;)

**Comment by markuspersson** [comment]
@Openarl Done. Some new line changes got added, hope that's fine ;)

I noticed a typo when I did the merge. In CalcSetup, line 30: `env.build.targerVersion`. Should be `targetVersion`. Thought I'd give you a heads-up.

**Comment by Openarl** [comment]
You don't need to add an option for the # of curses on the enemy; that's calculated automatically, and can be found as the CurseOnEnemy multiplier on the player.

**Comment by markuspersson** [comment]
Ah nice, thanks! Updated again with your suggestions :+1:

**Pull request merged**
