### PR TITLE
Add granted effects

### PR DESCRIPTION
**Pull request by eps1lon**
Feature implementation requested in #487 

This PR adds an aggregated description of GrantedEffectsPerLevel to the gem tooltip in the skills tab. This includes quality bonus at 20%.

For this to work I had to add some missing value parsers in statesdesc.

Once this is approved I would also add the description of support gems since those hold valuable information (e.g. can only support skills that hit).

The naming in the skills data is currently not coherent. This is a result of a wrong usage of the word "mod". That's why `qualityMods` and `effects` seems kind off redundant or ambiguous but I didn't want to touch existing data structure. Depending on how good refactoring tool support is in lua it might be a good idea to revisit this data structure and name things correctly so that everyone understands what is meant.

### CODE REVIEW

**Comment by Openarl** [comment]
You should have consulted with me before attempting this. Your approach differs considerably from what I intended to use, and there are numerous issues that preclude any possibility of merging this:
1. Your add-granted-effects branch was created from an out of date copy of the dev branch, which has created conflicts.
2. You haven't utilised the specialised stat description files that are used for certain skill types (such as curse_skill_stat_descriptions), and so the descriptions for many skills are wrong or incomplete.
3. Some details like the base damage multiplier for attacks are missing.
4. You're showing the value ranges from level 1 to 30, which is useless; it aught to be 1 to 20, but...
5. It is far more useful to show the user the values for the current level/quality, rather than the potential value ranges; so the program's gem tooltips should mirror those shown in-game, rather than what you see on the wiki.
6. To allow the program to replicate the game tooltip more easily, it was my intent that the stat translation would actually be performed by the program itself, with the skill files being augmented to contain the original stat names and values, which would then be combined during the calculation pass and stored for later translation. This however involves refactoring the translation code (it doesn't run on the user's system, so less effort was made to make it neat), and including the description files (or, more likely, Lua-fied versions of them to speed load times) with the program.

While I appreciate your willingness to help, this is not a task which I would have recommended be attempted by anyone other than myself. If you wish to continue working on it then that is up to you, but you're going to have to do better than this.

**Comment by eps1lon** [comment]
1. Branch was created from the latest  upstream dev branch. I don't know where the up-to-date one would be found. I just forked it today and the latest commit was made 4 days ago.
2.  I utilised them. I just forgot to include curse_stat. 
3. This PR was specifically targeted at GrantedEffects. Adding more descriptions would be to big of a PR I reckoned. 
4. I agree. I could've adjusted it.
5. Same as 4.
6. I agree but it also seemed out of scope since all the other translation was was already included in the Data/Skills file.

I'd like to continue work on this but since you immediately closed it without waiting for adjustments from my side I don't know how open you are to contributions.

**Comment by Openarl** [comment]
1. Believe me, it is out of date. The version of your branch on GitHub doesn't have any commits since 1.4.49 (we're currently on 1.4.62), which is causing conflicts. That's why I closed this PR, as I couldn't merge it even if I wanted to, and updating it with new commits wouldn't fix the issue. If you continue working on this, you'll need to restart on a properly updated branch, then submit another PR.
2. No, you didn't. I'm looking through the changes you made to the skill exporter, and you're using skill_stat_descriptions for all of them, which is incorrect. It is necessary to use skillpopup_stat_filters.txt; that'll tell you which description file to use for each active skill.
3. All the stats shown in the gem tooltip are found in GrantedEffectsPerLevel, including the base damage multiplier (it isn't listed in the StatsKeys, but the game probably turns it into a stat for display anyway).
6. It certainly isn't the easier solution, but otherwise you need to include the translations for every value at every level of every gem (as the translation sometimes changes as the gem levels up), which would take up a lot of space. Moving the stat description code into the program itself is something that's likely to happen eventually anyway, so I was looking to this for an excuse to get it done.

I'm sorry if I seem a little harsh, but I have high standards for this program, and a feature like this needs to be done properly, or not at all. That being said, I am impressed that you've gotten this far; just getting the export system working must have been a trial, as I haven't documented the process at all. So if you think you can handle it, then by all means keep working; I would love to have someone around who can handle tasks like this.

**Comment by eps1lon** [comment]
1. Yes you are correct. I clicked on fork and forgot that I already had a 2 month old fork. Github just silently ignored it :(
2.  I just used the same code from Export/mods and started with skill_stat as the root which includes all the other files. I'm now starting with  curse_stat which does seem to add all translations. Could you comment on a line of code where the translation is missing or wrong (not including curses; those are fixed locally)?
3. BaseDamage isn't a stat. I wanted to start with stats only and include other fields like BaseDamage and ManaMultiplier later.
4. I could start working on localisation at runtime. Exporting the stat files into lua file that can be understood by the program. I think that bundling runtime localisation and gem descrption might be to big of a PR. Is there maybe another part of the code that uses the stat files so we could include the runtime localisation there and then see how it works? Or any other part in the code that alredy does something similar?

From a usability standpoint I do think that displaying a aggregated description is better. I guess this program is mainly used to create big DPS numbers but emphasizing on the utility of support gems might not be a bad idea. But we can work this out later and see which options feels more useful and configuration is always another option.

If you are not satisfied with the code you have every right to criticize. It's your repository in the end. It just wasn't very encouraging for me when you immediately closed this PR without awaiting changes from my side. Though I totally understand that it seems noobish to get PRs from a 2 month old brand.

I already worked with pypoe for eps1lon/poe_mod_repository which I'm currently rewriting and I'm actively contributing to Omega2K/pypoe so all of this is not new for me.

**Comment by Openarl** [comment]
Regarding the stat desctiption files, you cannot just load one file and use that for every gem; many stats are described differently depending on the skill type, so you must select the correct description file for each active skill according to Metadata/StatDescriptions/skillpopup_stat_filters.txt, with all support gems using gem_stat_descriptions. Without doing so, many of the stats on aura, debuff, and minion skills will be incorrectly described.

The base damage multiplier is not amongst the stats, but a quick look through the stat description files uncovered a stat called "active_skill_attack_damage_final_permyriad" which can be used to display it.

At present, all the stat translations are done in the exporter because there's minimal redundancy in the output, and storing the stat IDs and values would actually take up more space than storing the descriptions. As such, there isn't anything else in the program that could utilise it at the moment, so this probably is the best opportunity to move that code into the program. It will make for a weighty PR if done together though, but I'd rather do the move myself; I'll probably be releasing an update tonight, so you may not need to wait long.

What exactly do you mean by 'aggregated description'?

**Comment by eps1lon** [comment]
I never noticed that. Just directly using the stat_description keys seemed to do the trick. But again I'd like to see an example where the same stat Id is described differently depending on the gem it affects. But then I only ever used them for mods.

Aggregated stats means for me the stat value range across all levels rather than the exact stat value for the currently selected level. Basically just like the wiki does it in the little summary box in the top right corner. 

Could you reference the commit in this PR once you pushed it to keep me posted?

**Comment by Openarl** [comment]
There's quite a few; an extreme example is "attack_speed_+%", which is described as:
1. "X% increased Attack Speed" on most active skills
2. "Supported Skills have X% increased Attack Speed" on support gems
3. "You and nearby allies gain X% increased Attack Speed" on auras (e.g Haste)
4. "Minions have X% increased Attack Speed" on minion skills (e.g Animate Weapon)
5. "Grants Minions X% increased Attack Speed" on Flesh Offering

The exact value for the current effective level of the gem needs to be visible, as that information is very useful in cases where there are modifiers to the gem level. One seldom uses gems that aren't level 20/21 anyway, so there's no point displaying the level 1 value. If you really need to see the full range, then you're better off visiting the wiki anyway, as it'll show you the exact values at every level.

The update is being pushed to tomorrow, but I'll let you know as soon as I'm done with it.

**Pull request closed without merging**
